### PR TITLE
PSR-7 support

### PR DESCRIPTION
**Pull request by navitronic**
This PR adds support for signing and verifying PSR-7, as opposed to Symfony requests.

This change is a BC break and will require a `4.0` release

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by navitronic** [comment]
*note:* relies on phpDoc changes in #13, so might look a touch messy right now.

**Comment by pda** [comment]
Let me know when #13 is merged and this PR is rebased onto the resulting master.

**Comment by rubensayshi** [comment]
tests are failing because the symfony `Request` does `::normalizeQueryString`:
```
* It builds a normalized query string, where keys/value pairs are alphabetized,
* have consistent escaping and unneeded delimiters are removed.
```

**Comment by rubensayshi** [comment]
@navitronic I've been awaiting this for a while now, if there's anything we can do to get this merged asap then please let me know !

**Comment by navitronic** [comment]
@rubensayshi This is now merged. I will update the README at some point today and release a `4.0`

**Comment by rubensayshi** [comment]
awesome thx !!

**Pull request merged**
