### PR TITLE
Add gitattributes file

### PR DESCRIPTION
**Pull request by vinkla**
Add gitattributes file for smaller download size.

### CODE REVIEW

**Comment by pda** [comment]
Thanks. I hadn't come across using [`.gitattributes`](http://git-scm.com/docs/gitattributes) for this. I assume composer/packagist uses it… and maybe GitHub download archives too?

I'd rather not strip out the `README.md`, though. Many times having documentation inside libraries on disk has saved me when I don't have internet access (airplanes etc).

**Comment by vinkla** [comment]
These files will still be there if you don't specify it in the composer file or when you install the package. The whole purpose of this is too make the download size smaller.

**Comment by vinkla** [comment]
Any update on this?

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
