### PR TITLE
php-cs-fixer normalized formatting etc.

### PR DESCRIPTION
**Pull request by pda**
Addendum to #13; automated reformatting by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

    $ php-cs-fixer --version
    PHP CS Fixer version 1.10 by Fabien Potencier

    $ php-cs-fixer fix src/
       1) Algorithm.php
       2) Context.php
       3) HeaderList.php
       4) HmacAlgorithm.php
       5) KeyStore.php
       6) KeyStoreInterface.php
       7) Signature.php
       8) SignatureParameters.php
       9) SignatureParametersParser.php
      10) Signer.php
      11) SigningString.php
      12) SymfonyRequestMessage.php
      13) Verification.php
      14) Verifier.php
    Fixed all files in 4.107 seconds, 6.250 MB memory used

### CODE REVIEW

**Comment by navitronic** [comment]
lgtm :shipit:

**Comment by vinkla** [comment]
What about integrating https://styleci.io?

**Comment by pda** [comment]
I'm not against that, but I'm not sure it's worth the extra moving parts for a low-churn codebase like this.

**Comment by vinkla** [comment]
Ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Can be useful to avoid having to run php-cs-fixer locally. You can get it to send you a pull request with cs fixes if you push some bad code.

**Pull request merged**
