### PR TITLE
PSR-7 Support

### PR DESCRIPTION
**Pull request by rubensayshi**
extended https://github.com/99designs/http-signatures-php/pull/19

 - added custom `HttpMessageFactory` to avoid query string being reordered.
 - added some more type hints for methods.

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by rubensayshi** [comment]
looking forward to seeing this merged, any feedback?

**Comment by rubensayshi** [comment]
ping @vinkla 

tests only fail because somehow my removal of php 5.3 from `.travis.yml` didn't 'work', maybe cuz it's a PR ...

**Comment by vinkla** [comment]
Yeah, some of the dependencies require `>=5.4`.

**Comment by vinkla** [comment]
The `psr7` package require at least `>=5.4.0`.

**Comment by rubensayshi** [comment]
@vinkla @navitronic could you guys review this and merge?

**Comment by vinkla** [comment]
IMO we should even drop 5.4. PHP 5.5 will also be see end of life soon.

**Comment by navitronic** [comment]
Hi @rubensayshi,

I'd pretty much missed this.

Will review over the weekend and get back to you.

cheers,

Adrian

**Comment by navitronic** [comment]
@rubensayshi Thanks again for this, I have merged this into my PR and am doing some tweaks to it, hoping to merge it into master and have a new release available soon.

**Comment by rubensayshi** [comment]
awesome! let me know if there's anything I can do to help, review or test!

also once you have it stable I can update https://github.com/99designs/http-signatures-guzzlehttp/pull/8 which also works as a good extra test before you merge it ;-)

**Pull request merged**
